### ISSUE TITLE
No module named 'dateutil' (Windows)

### ISSUE THREAD

**Issue by mortee** [cmallwitz/Financials-Extension#3]
When installing the extension v1.0.4, I got the following error:

> (com.sun.star.uno.RuntimeException) { { Message = "<class 'ImportError'>: No module named 'dateutil', traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 149, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 104, in getModuleFromUrl\X000a    exec(codeobject, mod.__dict__)\X000a  File \"C:\\Users\\mortee\\AppData\\Roaming\\LibreOffice\\4\\user\\uno_packages\\cache\\uno_packages\\lu5516wl77np.tmp_\\Financials-Extension-1.0.4.oxt\\financials.py\", line 11, in <module>\X000a    import dateutil.parser\X000a  File \"C:\\Program Files\\LibreOffice\\program\\uno.py\", line 356, in _uno_import\X000a    return _builtin_import(name, *optargs, **kwargs)\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

Windows 10 64 bit
LibreOffice 6.3.4.2 (x64)
Python 3.6.4

**Comment by cmallwitz** [comment]
Module datetime is a default package in most python deployments I have come accross.

I'm not sure how packages are managed for python on Windows (or how you deployed python in the first place) but you could look at some advice on it e.g. https://stackoverflow.com/questions/1449494/how-do-i-install-python-packages-on-windows 

I would expect some of the options involving pip or easy_install should resolve the issue for you

Good luck and let me know if it is working for you!
Christian

**Comment by mortee** [comment]
Well, yeah, turned out that LO comes with its own python installation on windows, and I had to install pip, and then the modules python-dateutil, pytz and pyparsing in that. Was a bit tricky, but ultimately I got it to work.

For future reference: the trick is that get-pip.py needs to be executed by the LO python interpreter from a cmd window with administrator rights, i.e.

`"c:\Program Files\LibreOffice\program\python.exe" c:\temp\get-pip.py`

And then calling pip.exe directly resulted in a not found dll for me, so I had to invoke pip from within python:

`python -m pip install python-dateutil pytz pyparsing`

After this, the extension installs without issues.

**Comment by cmallwitz** [comment]
Thanks for the feedback - yes, LO having its own python probably makes things a bit more complicated.

**Comment by dotpointer** [comment]
This is broken in latest Debian with LibreOffice 6.1.5.2, I am getting the same error.

Tried this - all executed fine:
`pip install DateTime`
`pip install python-dateutil`
`pip install pytz`
`pip install pyparsing`

Still getting the same error when I try to add the extension from the releases page.

The extension is then not listed, then after a restart it is, but it is faded out and it has an exclamation mark and the text "Error: the status for this extension is unknown".

How do I get this to work?

**Comment by cmallwitz** [comment]
I'm not exactly sure about python2 vs python3 (the later being used by LibreOffice) but the following steps got everything working for me on a fresh Debian 10.3 (as root):

- apt install python3-pip
- pip3 install python-dateutil
- pip3 install pytz
- pip3 install pyparsing

Please note: Google as a data source seems to have some issues currently - I'm looking into it... 

Thanks
Christian

**Comment by cmallwitz** [comment]
BTW I uploaded a new release 1.0.5 to address the Google issue.

**Comment by dotpointer** [comment]
`pip3 install pytz` together with 1.0.5 worked in Debian, all other dependencies were already satisfied.

I tested the examples.ods, the Google data source did not show any data but the Yahoo data source did. :+1:

But it is heavy, it hangs the whole desktop environment for 25 seconds.

**Comment by dotpointer** [comment]
Forgot the most important thing - thanks! :smile:

**Comment by cmallwitz** [comment]
Thanks! 

Re: performance there is a performance "penalty" of hitting the web of anything between 1-2 seconds (from what I have observed) per symbol. 

I tried to mitigate this a bit such that the data is cached when accessing different data points for the same symbol and by keeping the internet connection to the provider open between fetching data for different symbols but unfortunately can't do anything about the remote server response time.

Google has less data than Yahoo but slightly different symbol coverage, but you said your are not getting any data from Google? Release 1.0.5 has fixed that for me. Do you have some more details - maybe a specific symbol?

Cheers!

**Comment by dotpointer** [comment]
Good that you tried to mitigate it. Maybe a progress bar or something to show the updating process could stop the feeling that the program has hanged, but maybe an extension is not allowed to show such things. Best would be if the API:s you're using had support to send in multiple requests in one request and then get one response back with all that is needed.

When I try Google in the selector cell then all data cells shows `<Datacode.TIMESTAMP: 999>`.

![bild](https://user-images.githubusercontent.com/22545272/77950455-cdccd400-72c8-11ea-865b-54975e709e1d.png)

Off topic question, but in examples.ods E5 you have written `=VLOOKUP("NYSE:IBM";Identifiers; $C$3;0)`. Where is Identifiers coming from? I checked the Meta Data sheet tab and found the Identifiers cell there, but it wasn't bothered when I fiddled with the cell text - so it can't be that it is using? From what I have understood there should be a cell range specified in the place where Identifiers is located, so it must be some kind of constant defined somewhere?

**Comment by cmallwitz** [comment]
Are you sure you are using 1.0.5? The problem in your screen shot was fixed in that version (at least for me).

Re: E5 and VLOOKUP - "Identifiers" is a label/name in the Meta Data sheet - check the sheet and navigate around a little bit with the cursor: there is a select box (top left right under font select box) that shows by default the current cell position). If you click on the drop down you can see "Identifiers" - when you select it the area used for the VLOOKUP is highlighted.

**Comment by dotpointer** [comment]
Yes, I am using 1.0.5, the add-ons dialog also confirms it:
![bild](https://user-images.githubusercontent.com/22545272/78270131-b846ec80-750a-11ea-87ef-37751362c8bf.png)

Thanks, I found the select box, clicked Manage names... and found the dialog where Identifiers was set.

**Comment by cmallwitz** [comment]
There was actually a Debian specific issue: it only installs the users locale by default e.g. de_DE or en_GB, rather then a more complete set e.g. including en_US - the later was on my Ubuntu but not Debian. I only used it for some number conversion logic which wasn't really necessary.

So installing en_US.UTF-8 in your Debian installation or moving to the new release 1.0.6 should fix the issue you reported.

**Comment by dotpointer** [comment]
Updated both the extension and example to 1.0.6.

Now it looks like this - "saknas" is missing in Swedish:

![bild](https://user-images.githubusercontent.com/22545272/78511421-dd528e00-779c-11ea-9747-0b144fd01fe2.png)

**Comment by cmallwitz** [comment]
In English "saknas" would be "N/A", this is the value used by LibreOffice when the extension doesn't return any value (Python None)

First of all, a hint for using LibreCalc: if you want to refresh data you can press SHIFT-CTRL-F9 - this will force a recalculation of all formulas in all sheets. 

Starting with version 1.0.6 the extension saves some debug information under your user directory in a directory ".financials-extension": the HTML for each stock symbol is saved in a separate file (depending on source and ticker symbol). You can open it your favorite web browser (or other tools) to check if the page actually contained the information you are looking for. If it does the file "trace.log" has a record of all calls to the extension and the value returned to LibreOffice.

If all of that doesn't answer the missing data, please attache the relevant files here for me to take a look at!

**Comment by cmallwitz** [comment]
Added Windows install steps to readme - closing this issue.
